{
 "title": "System Performance Metrics - Overview (MetricsHub)",
 "description": "General OS performance metrics to assess the availability and performance of Linux and Windows systems. Leverages OpenTelemetry metrics collected with MetricsHub and stored in Prometheus.",
 "tags": [ "System Overview" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "filesystemFilter", "label": "Exclude Filesystem Types", "query": ".*tmpfs|nfs.*|overlay" },
   {
    "name": "system",
    "query": {
     "query": "label_values(system_uptime_seconds,os_type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview & Current Issues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Critical Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS_FOR_STATE{severity=\"critical\", alertname=~\"MetricsHub-System-.*\"})",
     "legendFormat": "Critical Alerts"
    }
   ]
  },
  {
   "title": "Current Issues",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "(count by (host_name) (metricshub_host_up{os_type=~\"$system\"} == 0)) \r\nor \r\n(count by (host_name) (metricshub_host_up{os_type=~\"$system\"}) * 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\r\n  count(ALERTS_FOR_STATE{severity=\"critical\", alertname=~\"MetricsHub-System-.*\"}) by (host_name)\r\n  or \r\n  (0 * count by (host_name) (system_uptime_seconds)) # This is used to make sure a column is always created\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\r\n  count(ALERTS_FOR_STATE{severity=\"warning\", alertname=~\"MetricsHub-System-.*\"}) by (host_name)\r\n  or \r\n  (0 * count by (host_name) (system_uptime_seconds)) # This is used to make sure a column is always created\r\n)",
     "legendFormat": "__auto"
    },
    { "expr": "system_uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Hosts",
   "type": "stat",
   "description": "Total number of monitored hosts.",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (host_name) (system_uptime_seconds))",
     "legendFormat": "Hosts"
    }
   ]
  },
  {
   "title": "Unhealthy Hosts",
   "type": "stat",
   "description": "Number of Hosts with at least one warning, one critical alert or one protocol down.",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\r\n  group by (host_name) (\r\n    (metricshub_host_up{os_type=~\"$system\"} == 0) or \r\n    (ALERTS_FOR_STATE{severity=\"critical\", alertname=~\"MetricsHub-System-.*\"}) or \r\n    (ALERTS_FOR_STATE{severity=\"warning\", alertname=~\"MetricsHub-System-.*\"})\r\n   )\r\n)   ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unhealthy Hosts (%)",
   "type": "stat",
   "description": "Percentage of Hosts with at least one warning, one critical alert or one protocol down.",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\r\n  count(\r\n    group by (host_name) (\r\n      (metricshub_host_up{os_type=~\"$system\"} == 0) or \r\n      (ALERTS_FOR_STATE{severity=\"critical\", alertname=~\"MetricsHub-System-.*\"}) or \r\n      (ALERTS_FOR_STATE{severity=\"warning\", alertname=~\"MetricsHub-System-.*\"})\r\n    )\r\n  ) \r\n  / \r\n  count(count by (host_name) (system_uptime_seconds))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "options": {
    "content": "<a href=\"https://metricshub.com/\" target=\"_blank\">\n  <div style=\"\n    display: block;\n    margin: 0 auto; \n    \n    background: transparent url(https://metricshub.com/images/logo-darkgrey.svg) no-repeat center center;\n    background-size: contain;\n    \n    width: 85px;   \n    height: 85px;\n    border-radius: 3px;\n  \">\n  </div>\n</a>"
   }
  },
  {
   "title": "Warnings",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS_FOR_STATE{severity=\"warning\", alertname=~\"MetricsHub-System-.*\"})",
     "legendFormat": "Warning Alerts"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 4 },
   "targets": [
    {
     "expr": "100 * (\r\n  count by (os_type) (\r\n    group by (host_name, os_type) (\r\n      (metricshub_host_up{os_type=~\"$system\"} == 0) or \r\n      ((ALERTS_FOR_STATE{severity=~\"critical|warning\", alertname=~\"MetricsHub-System-.*\"}) \r\n       * on(host_name) group_left(os_type) \r\n       (group by (host_name, os_type) (system_uptime_seconds{os_type=~\"$system\"})))\r\n    )\r\n  ) \r\n  / \r\n  count by (os_type) (count by (host_name, os_type) (system_uptime_seconds{os_type=~\"$system\"}))\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (os_type) (system_uptime_seconds)",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 * count by (os_type) (group by (host_name, os_type) (system_uptime_seconds)) / scalar(count(count by (host_name) (system_uptime_seconds)))",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (os_type) (group by (host_name, os_type) (system_uptime_seconds))",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (os_type) (\r\n    group by (host_name, os_type) (\r\n      (metricshub_host_up{os_type=~\"$system\"} == 0) or \r\n      ((ALERTS_FOR_STATE{severity=~\"critical|warning\", alertname=~\"MetricsHub-System-.*\"}) \r\n       * on(host_name) group_left(os_type) \r\n       (group by (host_name, os_type) (metricshub_host_up{os_type=~\"$system\"})))\r\n    )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Protocols",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(metricshub_host_up{os_type=~\"$system\"} == 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  { "title": "Current Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 } },
  { "title": "Hosts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "count(metricshub_host_up == 0) by (host_name)",
     "legendFormat": "__auto"
    },
    { "expr": "system_uptime_seconds", "legendFormat": "__auto" },
    {
     "expr": "(\r\n  count(ALERTS_FOR_STATE{severity=\"critical\", alertname=~\"MetricsHub-System-.*\"}) by (host_name)\r\n  or \r\n  (0 * count by (host_name) (system_uptime_seconds)) # This is used to make sure a column is always created\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\r\n  count(ALERTS_FOR_STATE{severity=\"warning\", alertname=~\"MetricsHub-System-.*\"}) by (host_name)\r\n  or \r\n  (0 * count by (host_name) (system_uptime_seconds)) # This is used to make sure a column is always created\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(system_memory_utilization_ratio{system_memory_state!=\"free\"}) by (host_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\r\n  sum by (host_name) (\r\n    rate(system_cpu_time_seconds_total{system_cpu_state!=\"idle\"}[5m])\r\n  )\r\n/\r\n  sum by (host_name) (\r\n    rate(system_cpu_time_seconds_total[5m])\r\n  )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(metricshub_host_up) by (host_name) * 100 / count(metricshub_host_up) by (host_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\r\n  # Case 1: Ping is down for selected OS types\r\n  (max by (host_name) (metricshub_host_up{protocol=\"ping\"} == 0)) - 1\r\n  or\r\n  # Case 2: Ping is up for selected OS types → Show response time\r\n  (max by (host_name) (metricshub_host_up{protocol=\"ping\"} == 1))\r\n  * on(host_name)\r\n  (max by (host_name) (metricshub_host_response_time_seconds{protocol=\"ping\"}) * 1000)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Filesystems", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Filesystems - Top 5 Utilization",
   "type": "table",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_join(\r\n     sum(system_filesystem_utilization_ratio{system_filesystem_state=~\"used|reserved\"}) by (site, host_name, system_device),\r\n     \"id\", \":\", \"host_name\", \"system_device\"\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(\r\n    sum(system_filesystem_usage_bytes{system_filesystem_state=~\"used|reserved|free\"}) by (site, host_name, system_device),\r\n    \"id\", \":\", \"host_name\", \"system_device\"\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(\r\n    sum by (site, host_name, system_device) (\r\n        system_filesystem_usage_bytes{system_filesystem_state=~\"free\"}),\r\n    \"id\", \":\", \"host_name\", \"system_device\"\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(\r\n  sum by (site, host_name, system_device) (\r\n    system_filesystem_utilization_ratio{system_filesystem_state=~\"used|reserved\", system_filesystem_type!~\"$filesystemFilter\"}),\r\n  \"id\", \":\", \"host_name\", \"system_device\"\r\n)\r\n-\r\nlabel_join(\r\n  sum by (site, host_name, system_device) (\r\n    system_filesystem_utilization_ratio{system_filesystem_state=~\"used|reserved\", system_filesystem_type!~\"$filesystemFilter\"} offset $__range\r\n  ),\r\n  \"id\", \":\", \"host_name\", \"system_device\"\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(\r\n     sum by (site, host_name, system_device) (\r\n           system_filesystem_utilization_ratio{system_filesystem_state=~\"used|reserved\", system_filesystem_type !~\"$filesystemFilter\"}\r\n     ),\r\n     \"id\", \":\", \"host_name\", \"system_device\"\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(\r\n     sum by (site, host_name, system_device) (\r\n            delta(system_filesystem_usage_bytes{system_filesystem_state=\"used\"}[$__range]) / $__range_s \r\n            ),\r\n     \"id\", \":\", \"host_name\", \"system_device\"\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(\r\n  (\r\n    sum by (site, host_name, system_device) (\r\n      system_filesystem_usage_bytes{system_filesystem_state=\"free\"}\r\n    )\r\n    / ignoring(system_filesystem_state)\r\n    sum by (site, host_name, system_device) (\r\n      delta(system_filesystem_usage_bytes{system_filesystem_state=\"used\"}[$__range]) / $__range_s\r\n    )\r\n  ) \r\n  and ignoring(system_filesystem_state)\r\n  sum by (site, host_name, system_device) (\r\n    delta(system_filesystem_usage_bytes{system_filesystem_state=\"used\"}[$__range])\r\n  ) > 0,\r\n  \"id\", \":\", \"host_name\", \"system_device\"\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Earliest Saturation Time",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 36 },
   "targets": [
    {
     "expr": "bottomk(5,\r\n  label_join(\r\n    (\r\n      sum by (site, host_name, system_device) (\r\n        system_filesystem_usage_bytes{system_filesystem_state=\"free\"}\r\n      )\r\n      / ignoring(system_filesystem_state)\r\n      sum by (site, host_name, system_device) (\r\n        delta(system_filesystem_usage_bytes{system_filesystem_state=\"used\"}[$__range]) / $__range_s\r\n      )\r\n    ) \r\n    and ignoring(system_filesystem_state)\r\n    sum by (site, host_name, system_device) (\r\n      delta(system_filesystem_usage_bytes{system_filesystem_state=\"used\"}[$__range])\r\n    ) > 0,\r\n    \"id\", \":\", \"host_name\", \"system_device\"\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Disk Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Top Drives by Traffic",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (site, host_name, system_device) (rate(system_disk_io_bytes_total[$__range])))",
     "legendFormat": "{{host_name}} - {{system_device}}"
    }
   ]
  },
  {
   "title": "Top Drives by Utilization",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5,\r\n  max by (host_name, system_device) (rate(system_disk_io_time_seconds_total[$__range]))\r\n)",
     "legendFormat": "{{host_name}} - {{system_device}}"
    }
   ]
  },
  {
   "title": "Total Host Disk Activity - Heatmap",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (host_name) (increase(system_disk_io_bytes_total[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Top Network Interfaces by Traffic",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (site, host_name, network_interface_name) (rate(system_network_io_bytes_total[$__range])))",
     "legendFormat": "{{host_name}} - {{network_interface_name}}"
    }
   ]
  },
  {
   "title": "Top Network Interfaces by Utilization",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5,\r\n  max by (host_name, network_interface_name) (rate(system_network_io_bytes_total[$__range])) / on(host_name, network_interface_name)\r\n  max by (host_name, network_interface_name) (system_network_bandwidth_limit_bytes)\r\n)",
     "legendFormat": "{{host_name}} - {{network_interface_name}}"
    }
   ]
  },
  {
   "title": "Total Host Network Activity - Heatmap",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (host_name) (increase(system_network_io_bytes_total[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "MetricsHub Agents Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "type": "table",
   "gridPos": { "h": 4, "w": 22, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "last_over_time(timestamp(metricshub_agent_info)[6h:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dashboard",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  }
 ]
}