{
 "title": "MetricsHub System",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "Data Source", "query": "prometheus" },
   { "name": "site", "label": "Site", "query": { "query": "label_values(site)" } },
   {
    "name": "host_id",
    "label": "Host",
    "query": {
     "query": "label_values({site=~\"$site\", connector_id=~\"Linux|Windows\"},host_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Host Global Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": {
    "content": "\n<img src=\"https://metricshub.com/images/logo-darkgrey.svg\" alt=\"MetricsHub\" width=\"150\" height=\"150\">\n"
   }
  },
  {
   "title": "Host Information",
   "type": "table",
   "gridPos": { "h": 4, "w": 22, "x": 2, "y": 1 },
   "targets": [
    {
     "expr": "system_uptime{site=\"$site\", host_id=\"$host_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Core",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (system_cpu_utilization_ratio{site=\"$site\", host_id=\"$host_id\", system_cpu_state=\"system\"})",
     "legendFormat": "CPU Core"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_limit_bytes{site=\"$site\", host_id=\"$host_id\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Volume",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "system_volume_size_bytes{site=\"$site\", host_id=\"$host_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "system_volume_used_bytes{site=\"$site\", host_id=\"$host_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "system_filesystem_usage_bytes{site=\"$site\", host_id=\"$host_id\", system_filesystem_state=\"free\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "targets": [
    {
     "expr": "system_network_io_bytes_total{site=\"$site\", host_id=\"$host_id\", network_io_direction=\"receive\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Host Health",
   "type": "table",
   "gridPos": { "h": 4, "w": 22, "x": 2, "y": 9 },
   "targets": [
    {
     "expr": "metricshub_host_up{site=\"$site\", id=\"$host_id\", protocol!=\"ping\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "metricshub_host_up{site=\"$site\", id=\"$host_id\", protocol=\"ping\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "metricshub_connector_status{site=\"$site\", host_id=\"$host_id\", connector_id=~\"Linux|Windows\"} == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU Time",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "seconde" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (system_cpu_state) (rate(system_cpu_time_seconds_total{site=\"$site\", host_id=~\"$host_id\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Core Utilization",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(system_cpu_time_seconds_total{site=\"$site\", host_id=~\"$host_id\", system_cpu_state!=\"idle\"}[2m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(sum(rate(system_cpu_time_seconds_total{site=\"$site\", host_id=~\"$host_id\", system_cpu_state!=\"idle\"}[3m])) by (name))",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Memory Usage",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_usage_bytes{host_id=~\"$host_id\", site=\"$site\" }",
     "legendFormat": "{{system_memory_usage}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (system_memory_utilization_ratio{host_id=\"$host_id\", system_memory_usage=\"used\", site=\"$site\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 4, "x": 20, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_usage_bytes{host_id=~\"$host_id\", site=\"$site\", system_memory_usage=~\"cached|buffers\"}",
     "legendFormat": "{{system_memory_usage}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "type": "table",
   "gridPos": { "h": 13, "w": 4, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "system_network_io_bytes_total{site=\"$site\", host_id=\"$host_id\", network_io_direction=\"receive\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 18, "x": 4, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "-(irate(system_network_io_bytes_total{site=\"$site\", host_id=\"$host_id\", network_io_direction=\"receive\"}[5m]))",
     "legendFormat": "Receive from {{id}}"
    },
    {
     "expr": "irate(system_network_io_bytes_total{site=\"$site\", host_id=\"$host_id\", network_io_direction=\"transmit\"}[5m])",
     "legendFormat": "Transmit from {{id}}"
    }
   ]
  },
  {
   "title": "Network Error Ratio",
   "type": "stat",
   "gridPos": { "h": 13, "w": 2, "x": 22, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (network_io_direction) (system_network_errors_total{site=\"$site\", host_id=\"$host_id\"})\r\n/\r\nsum by (network_io_direction) (system_network_io_bytes_total{site=\"$site\", host_id=\"$host_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Filesystem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Filesystem",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "system_filesystem_usage_bytes{site=\"$site\", host_id=\"$host_id\", system_filesystem_state=\"free\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "system_filesystem_usage_bytes{site=\"$site\", host_id=\"$host_id\", system_filesystem_state=\"used\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Disk Activity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate (system_disk_operations_bytes{site=\"$site\", host_id=\"$host_id\"}[3m])",
     "legendFormat": "{{id}} {{direction}}"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_volume_used_ratio{site=\"$site\", host_id=\"$host_id\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Volum",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "system_volume_size_bytes{site=\"$site\", host_id=\"$host_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "system_volume_used_bytes{site=\"$site\", host_id=\"$host_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Agent Informations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "timestamp(metricshub_agent_info)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}