{
 "title": "Hardware Host (MetricsHub)",
 "description": "Collect hardware health and performance metrics as well as sustainability KPIs of your hosts with MetricsHub®; visualize the gathered telemetry data in the comprehensive Hardware Host (MetricsHub) dashboard.\r\nMetricsHubs collects metrics from servers (Cisco, Dell, HPE, Huawei, IBM Lenovo, SuperMicro, etc.), storage systems (NetApp, Dell EMC, Hitachi, HPE, IBM, Pure, Huawei, etc.), network devices (Cisco, Aruba, Dell, HP, F5, Juniper, Oracle) and other equipment like PDUs, UPS from APC, Raritan, Eaton, etc.",
 "tags": [ "hw_host" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hw_type",
    "query": {
     "query": "label_values(hw_status{site=~\"$site\", host_name=~\"$host_name\"}, hw_type)"
    }
   },
   {
    "name": "site",
    "label": "Site",
    "query": {
     "query": "label_values(metricshub_host_configured,site)"
    }
   },
   {
    "name": "host_name",
    "label": "Host Name",
    "query": {
     "query": "label_values(metricshub_host_configured{site=~\"$site\"},host_name)"
    }
   },
   {
    "name": "agent",
    "query": {
     "query": "label_values(metricshub_host_configured{site=\"$site\", host_name=\"$host_name\"},agent_host_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"\">\r\n  <center>${host_name}</center>\r\n</h1>"
   }
  },
  {
   "title": "Host Information, Alerts and Protocols Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }
  },
  {
   "title": "Host Type",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "hw_status{site=~\"$site\", host_name=~\"$host_name\", hw_type=\"enclosure\"}"
    }
   ]
  },
  {
   "title": "Vendor and Model",
   "type": "stat",
   "description": "The vendor and model information of the host (when available).",
   "gridPos": { "h": 3, "w": 7, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "hw_status{site=~\"$site\", host_name=~\"$host_name\", hw_type=\"enclosure\"}"
    }
   ]
  },
  {
   "title": "Critical Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS_FOR_STATE{severity=\"critical\", site=~\"$site\", host_name=~\"$host_name\", alertname=~\"MetricsHub-Hardware-.*\"})",
     "legendFormat": "Critical Alerts"
    }
   ]
  },
  {
   "title": "Current Alerts",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "ALERTS_FOR_STATE{host_name=~\"$host_name\", site=~\"$site\"}"
    }
   ]
  },
  {
   "title": "CPU Max Speed",
   "type": "stat",
   "description": "The maximum speed of the host's CPU (when available).",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(hw_cpu_speed_limit_hertz{site=~\"$site\", host_name=~\"$host_name\"})",
     "legendFormat": "CPU Maximum Speed"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "description": "The total memory size of the host (when available).",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hw_memory_limit_bytes{site=~\"$site\", host_name=~\"$host_name\"})",
     "legendFormat": "Memory Size"
    }
   ]
  },
  {
   "title": "Disk Size",
   "type": "stat",
   "description": "The total disk size of the host (when available).",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hw_physical_disk_size_bytes{site=~\"$site\", host_name=~\"$host_name\"})",
     "legendFormat": "Disk Size"
    }
   ]
  },
  {
   "title": "Warning Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS_FOR_STATE{severity=\"warning\", site=~\"$site\", host_name=~\"$host_name\", alertname=~\"MetricsHub-Hardware-.*\"})",
     "legendFormat": "Warning Alerts"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum_over_time(metricshub_host_up{host_name=\"$host_name\"}[$__range]) / count_over_time(metricshub_host_up{host_name=\"$host_name\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "min_over_time(\r\n  (\r\n    (metricshub_host_response_time_seconds{host_name=\"$host_name\"} > 0) * 1 or\r\n    (metricshub_host_response_time_seconds{host_name=\"$host_name\"} <= 0) * +Inf\r\n  )[$__range:1m]\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(metricshub_host_response_time_seconds{host_name=\"$host_name\"}[$__range])",
     "legendFormat": "{{protocol}}"
    },
    {
     "expr": "max_over_time(metricshub_host_response_time_seconds{host_name=\"$host_name\"}[$__range])",
     "legendFormat": "{{protocol}}"
    },
    {
     "expr": "metricshub_host_response_time_seconds{host_name=\"$host_name\"}",
     "legendFormat": "{{protocol}}"
    },
    {
     "expr": "metricshub_host_up{site=\"$site\", host_name=\"$host_name\"}",
     "legendFormat": "{{protocol}}"
    },
    {
     "expr": "metricshub_host_up{site=\"$site\", host_name=\"$host_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Power, Costs and CO₂ Emissions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Power * P.U.E",
   "type": "stat",
   "description": "The host's current power usage multiplied by the site's PUE.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hw_host_power_watts{site=~\"$site\", host_name=~\"$host_name\"} * scalar(avg(hw_site_pue_ratio{site=~\"$site\"}))",
     "legendFormat": "Power * P.U.E"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "description": "The host's power consumption displayed as a graph.",
   "gridPos": { "h": 8, "w": 8, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "hw_host_power_watts{site=~\"$site\", host_name=~\"$host_name\"}",
     "legendFormat": "Power Consumption"
    }
   ]
  },
  {
   "title": "Power per Device Type",
   "type": "piechart",
   "description": "The breakdown of the host's energy consumption per components.",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (hw_type) (hw_energy_joules_total{site=~\"$site\", host_name=~\"$host_name\"})",
     "legendFormat": "{{hw_type}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 15 },
   "options": {
    "content": "<h6 style=\"background-color:yyyyy\"><center>Today's Live Data</center></h6>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 15 },
   "options": {
    "content": "<h6 style=\"background-color:yyyy\"><center>Cumulative Consumption</center></h6>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 15 },
   "options": {
    "content": "<h6 style=\"background-color:DimGreen\"><center>Cumulative Cost</center></h6>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 15 },
   "options": {
    "content": "<h5 style=\"background-color:yyyyy\"><center>Cumulative CO₂</center></h5>"
   }
  },
  {
   "title": "Daily Consumption",
   "type": "stat",
   "description": "Today's power consumption for the host.",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(hw_host_energy_joules_total{site=~\"$site\", host_name=~\"$host_name\"}[$__range])) * avg_over_time(avg(hw_site_pue_ratio{site=~\"$site\"})[$__range:5m]) / 3600 ",
     "legendFormat": "Today's Live Consumption"
    }
   ]
  },
  {
   "title": "Daily",
   "type": "stat",
   "description": "The overall power consumption reported for the host in last 24 hours.\n\nIf less than 24 hours of data is available, this value is estimated based on the past collected data.",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(hw_host_power_watts{site=~\"$site\", host_name=~\"$host_name\"}[1d:5m]) * scalar(avg_over_time(avg(hw_site_pue_ratio{site=~\"$site\"})[1d:5m])) * 24",
     "legendFormat": "Daily Consumption"
    }
   ]
  },
  {
   "title": "Daily",
   "type": "stat",
   "description": "The overall energy cost reported for the host during the last 24 hours.\n\nIf less than 24 hours of data is available, this value is estimated based on the past collected data.",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(hw_host_power_watts{site=~\"$site\", host_name=~\"$host_name\"}[1d:5m]) * scalar(avg_over_time(avg(hw_site_pue_ratio{site=~\"$site\"})[1d:5m])) * scalar(avg_over_time(avg(hw_site_electricity_cost{site=~\"$site\"})[1d:5m])) * 24 / 1000",
     "legendFormat": "Daily Cost"
    }
   ]
  },
  {
   "title": "Daily",
   "type": "stat",
   "description": "The overall CO₂ emitted by the host during the last 24 hours.\n\nIf less than 24 hours of data is available, this value is estimated based on the past collected data.",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(hw_host_power_watts{site=~\"$site\", host_name=~\"$host_name\"}[1d:5m]) * scalar(avg_over_time(avg(hw_site_pue_ratio{site=~\"$site\"})[1d:5m])) * scalar(avg_over_time(avg(hw_site_carbon_intensity_grams{site=~\"$site\"})[1d:5m])) * 24 / 1000 / 1000",
     "legendFormat": "Daily CO₂ Emissions"
    }
   ]
  },
  {
   "title": "Power",
   "type": "stat",
   "description": "The host's current power consumption.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hw_host_power_watts{site=~\"$site\", host_name=~\"$host_name\"}",
     "legendFormat": "Power"
    }
   ]
  },
  {
   "title": "Cost",
   "type": "stat",
   "description": "Today's energy cost for the host.",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(hw_host_energy_joules_total{site=~\"$site\", host_name=~\"$host_name\"}[$__range])) * avg_over_time(avg(hw_site_pue_ratio{site=~\"$site\"})[$__range:5m]) * avg_over_time(avg(hw_site_electricity_cost{site=~\"$site\"})[$__range:5m]) / 3600 / 1000",
     "legendFormat": "Today's Live Cost"
    }
   ]
  },
  {
   "title": "Monthly",
   "type": "stat",
   "description": "The overall power consumption reported for the host during the last 30 days.\n\nIf less than 30 days of data is available, this value is estimated based on past collected data.",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(hw_host_power_watts{site=~\"$site\", host_name=~\"$host_name\"}[30d:1h]) * scalar(avg_over_time(avg(hw_site_pue_ratio{site=~\"$site\"})[30d:1h])) * 24 * 30.437",
     "legendFormat": "Monthly Consumption"
    }
   ]
  },
  {
   "title": "Monthly",
   "type": "stat",
   "description": "The overall energy cost reported for the host during the last 30 days.\n\nIf less than 30 days of data is available, this value is estimated based on past collected data.",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(hw_host_power_watts{site=~\"$site\", host_name=~\"$host_name\"}[30d:1h]) * scalar(avg_over_time(avg(hw_site_pue_ratio{site=~\"$site\"})[30d:1h])) * scalar(avg_over_time(avg(hw_site_electricity_cost{site=~\"$site\"})[30d:1h])) * 30.437 * 24 / 1000",
     "legendFormat": "Monthly Cost"
    }
   ]
  },
  {
   "title": "Monthly",
   "type": "stat",
   "description": "The overall CO₂ emitted by the host during the last 30 days.\n\nIf less than 30 days of data is available, this value is estimated based on the past collected data.",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(hw_host_power_watts{site=~\"$site\", host_name=~\"$host_name\"}[30d:1h]) * scalar(avg_over_time(avg(hw_site_pue_ratio{site=~\"$site\"})[30d:1h])) * scalar(avg_over_time(avg(hw_site_carbon_intensity_grams{site=~\"$site\"})[30d:1h])) * 30.467 * 24 / 1000 / 1000",
     "legendFormat": "Monthly CO₂ Emissions"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "stat",
   "description": "The type of power consumption reading:\n- Measured, if the value is reported by the manufacturer's agent\n- Estimated, if the value is estimated by Hardware Sentry based on the discovered devices and their current usage.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "hw_host_power_watts{site=~\"$site\", host_name=~\"$host_name\"}",
     "legendFormat": "Power Consumption Reading Type"
    }
   ]
  },
  {
   "title": "CO₂ Emissions",
   "type": "stat",
   "description": "Today's CO₂ emitted by the host.",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(hw_host_energy_joules_total{site=~\"$site\", host_name=~\"$host_name\"}[$__range])) * avg_over_time(avg(hw_site_pue_ratio{site=~\"$site\"})[$__range:5m]) * avg_over_time(avg(hw_site_carbon_intensity_grams{site=~\"$site\"})[$__range:5m]) / 3600 / 1000 / 1000",
     "legendFormat": "Today's Live CO₂ Emissions"
    }
   ]
  },
  {
   "title": "Yearly",
   "type": "stat",
   "description": "The overall power consumption reported for the host during the last year.\n\nIf less than 365 days of data is available, this value is estimated based on past collected data.",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(hw_host_power_watts{site=~\"$site\", host_name=~\"$host_name\"}[1y:1d]) * scalar(avg_over_time(avg(hw_site_pue_ratio{site=~\"$site\"})[60d:1d])) * 24 * 365",
     "legendFormat": "Yearly Consumption"
    }
   ]
  },
  {
   "title": "Yearly",
   "type": "stat",
   "description": "The overall energy cost reported for the host in the past year.\n\nIf less than 365 days of data is available, this value is estimated based on past collected data.",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(hw_host_power_watts{site=~\"$site\", host_name=~\"$host_name\"}[1y:1d]) * scalar(avg_over_time(avg(hw_site_pue_ratio{site=~\"$site\"})[60d:1d])) * scalar(avg_over_time(avg(hw_site_electricity_cost{site=~\"$site\"})[1y:1d])) * 365 * 24 / 1000",
     "legendFormat": "Yearly Cost"
    }
   ]
  },
  {
   "title": "Yearly",
   "type": "stat",
   "description": "The overall CO₂ emitted by the host during the past year.\n\nIf less than 365 days of data is available, this value is estimated based on past collected data.",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(hw_host_power_watts{site=~\"$site\", host_name=~\"$host_name\"}[1y:1d]) * scalar(avg_over_time(avg(hw_site_pue_ratio{site=~\"$site\"})[60d:1d])) * scalar(avg_over_time(avg(hw_site_carbon_intensity_grams{site=~\"$site\"})[1y:1d])) * 365 * 24 / 1000 / 1000 / 1000",
     "legendFormat": "Yearly CO₂ Emissions"
    }
   ]
  },
  { "title": "Devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Monitored Devices",
   "type": "stat",
   "description": "The total number of discovered devices and sensors per type.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by (hw_type) (hw_status{site=~\"$site\", host_name=\"$host_name\", state=\"present\"})",
     "legendFormat": "{{ name}}"
    }
   ]
  },
  {
   "title": "Errors per Hour",
   "type": "heatmap",
   "description": "The number of detected errors per hour and component type (when available).",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(hw_errors_total{site=~\"$site\", host_name=~\"$host_name\"}[1h])) by (hw_type)",
     "legendFormat": "{{hw_type}}"
    }
   ]
  },
  {
   "title": "Monitored Devices",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "label_join(hw_status{site=~\"$site\", host_name=~\"$host_name\", state=\"ok\"} > 0 or hw_status{site=~\"$site\", host_name=~\"$host_name\",  state=\"degraded\"} > 0 or hw_status{site=~\"$site\", host_name=~\"$host_name\", state=\"failed\"} > 0, \"device_id\", \"_\", \"hw_type\", \"id\")"
    },
    {
     "expr": "label_join(hw_status{site=~\"$site\", host_name=~\"$host_name\", state=\"present\"}, \"device_id\", \"_\", \"hw_type\", \"id\")"
    },
    {
     "expr": "label_join(hw_status{site=~\"$site\", host_name=~\"$host_name\", state=\"predicted_failure\"}, \"device_id\", \"_\", \"hw_type\", \"id\")"
    }
   ]
  },
  { "title": "Temperatures and Fans", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Ambient ",
   "type": "stat",
   "description": "The current estimated internal temperature of the host.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hw_host_ambient_temperature_celsius{site=~\"$site\", host_name=~\"$host_name\"}",
     "legendFormat": "Ambient Temperature"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "description": "The reading of the host's temperature sensors (when available).",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "hw_temperature_celsius{site=~\"$site\", host_name=~\"$host_name\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "hw_host_ambient_temperature_celsius{site=~\"$site\", host_name=~\"$host_name\"}",
     "legendFormat": "Ambient"
    }
   ]
  },
  {
   "title": "Fans Speed",
   "type": "timeseries",
   "description": "The reading of the host's fans speed (when available).",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "expr": "hw_fan_speed_rpm{site=~\"$site\", host_name=~\"$host_name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Heating Margin",
   "type": "stat",
   "description": "The number of degrees Celsius (°C) remaining before the temperature reaches the closest warning temperature threshold of the host.\n\nA value of 0 indicates a critical temperature.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "hw_host_heating_margin_celsius{site=~\"$site\", host_name=~\"$host_name\"}",
     "legendFormat": "Heating Margin"
    }
   ]
  },
  {
   "title": "Avg Fan Speed",
   "type": "stat",
   "description": "The average speed of all the host's fans.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(hw_fan_speed_rpm{site=~\"$site\", host_name=~\"$host_name\"})",
     "legendFormat": "Average Fan Speed"
    }
   ]
  },
  { "title": " Network ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Total Traffic (bytes/s)",
   "type": "timeseries",
   "description": "Data transmitted and received by the host.\n\nPositive values correspond to transmitted data.\nNegative values correspond to received data.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(hw_network_io_bytes_total{site=~\"$site\", host_name=~\"$host_name\", direction=\"transmit\"}[5m]))",
     "legendFormat": "Transmitted"
    },
    {
     "expr": "sum(rate(hw_network_io_bytes_total{site=~\"$site\", host_name=~\"$host_name\", direction=\"receive\"}[5m]))",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Network Links",
   "type": "table",
   "description": "The network interfaces and their current link status (plugged or unplugged).",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "hw_status{site=~\"$site\", host_name=~\"$host_name\", hw_type=\"network\", state=\"present\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hw_network_up{site=~\"$site\", host_name=~\"$host_name\"}"
    }
   ]
  },
  {
   "title": "Max Error Ratio",
   "type": "stat",
   "description": "The highest network interface error ratio (total traffic vs errors).\n\nThis value should be at 0% or as close to 0% as possible.",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hw_errors_total{site=\"$site\", host_name=\"$host_name\", hw_type=\"network\"})\r\n/ \r\n(sum(hw_network_packets_total{site=\"$site\", host_name=\"$host_name\", direction=\"receive\"})\r\n+ sum(hw_network_packets_total{site=\"$site\", host_name=\"$host_name\", direction=\"transmit\"}) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bandwidth Utilization",
   "type": "timeseries",
   "description": "The network interfaces bandwidth utilization.\n\nThe bandwidth utilization should stay under 90% at all times.",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "hw_network_bandwidth_utilization_ratio{site=~\"$site\", host_name=~\"$host_name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "CPUs, Voltage and Batteries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "CPUs Speed and Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "avg(hw_cpu_speed_hertz{site=~\"$site\", host_name=~\"$host_name\"})",
     "legendFormat": "Speed"
    },
    {
     "expr": "sum(rate(hw_energy_joules_total{site=~\"$site\", host_name=~\"$host_name\", hw_type=\"cpu\"}[5m]))",
     "legendFormat": " Consumption"
    }
   ]
  },
  {
   "title": "Voltages",
   "type": "timeseries",
   "description": "The reading of the host's voltage sensors (when available).",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "hw_voltage_volts{site=~\"$site\", host_name=~\"$host_name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "timeseries",
   "description": "The percentage of battery charge (when available).",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "hw_battery_charge_ratio{site=~\"$site\", host_name=~\"$host_name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Disks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Logical Disks",
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "hw_logical_disk_limit_bytes{site=~\"$site\", host_name=~\"$host_name\"}",
     "legendFormat": "{{ name}}"
    }
   ]
  },
  {
   "title": "Endurance Remaining",
   "type": "timeseries",
   "description": "The disks remaining lifetime in percentage.\n\nA value lower than 3% indicates that the disk should be replaced.",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "hw_physical_disk_endurance_utilization_ratio{site=~\"$site\", host_name=~\"$host_name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Monitoring Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Connectors",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "metricshub_connector_status{site=~\"$site\", host_name=~\"$host_name\"}"
    }
   ]
  },
  { "title": "Hardware Sentry Agent Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "Collect Started",
   "type": "stat",
   "description": "Time since the monitoring of this host by Hardware Sentry was started.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min_over_time(timestamp(metricshub_host_configured{site=~\"$site\", host_name=\"$host_name\"})[1y:1d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 18, "x": 3, "y": 90 },
   "targets": [
    {
     "expr": "last_over_time(timestamp(metricshub_agent_info{agent_host_name=\"$agent\"})[6h:])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Dashboard Version", "type": "stat", "gridPos": { "h": 3, "w": 3, "x": 21, "y": 90 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } }
 ]
}