{
 "title": "Hardware Main (Hardware Sentry)",
 "tags": [ "hw_main" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "site", "label": "site", "query": { "query": "label_values(site)" } }
  ]
 },
 "panels": [
  { "title": "Overall Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hosts",
   "type": "stat",
   "description": "The number of hosts currently configured to be monitored.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(present_over_time(hardware_sentry_host_configured[1h]))",
     "legendFormat": "Hosts"
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "stat",
   "description": "The percentage of monitored hosts.\n\nA monitored host is a host with at least one responding connector.",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max by (host_id, site) (hardware_sentry_connector_status{state=\"ok\"} == 1)) / sum(present_over_time(hardware_sentry_host_configured[1h]))",
     "legendFormat": "Coverage"
    }
   ]
  },
  {
   "title": "Critical Alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS_FOR_STATE{severity=\"critical\"})",
     "legendFormat": "Critical Alerts"
    }
   ]
  },
  {
   "title": "Warning Alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS_FOR_STATE{severity=\"warn\"})",
     "legendFormat": "Warning Alerts"
    }
   ]
  },
  {
   "title": "Current Alerts",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "ALERTS_FOR_STATE{site != \"\", host_name != \"\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "options": {
    "content": "<a href=\"https://www.sentrysoftware.com/products/hardware-sentry-opentelemetry-collector.html\" target=\"_blank\">\n<div style=\"background: #76a600 url(https://dl.sentrysoftware.com/public/otel-dl-link.png) no-repeat center; background-size: contain; margin: 0; padding: 0px; border-radius: 3px; height: 100%; width: 100%;\">\n</div>\n</a>"
   }
  },
  { "title": "Power, Cost and CO₂ Emissions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total Power * PUE",
   "type": "stat",
   "description": "Total current power usage across all sites, multiplied by the site's PUE.\n\nThis number represents the actual power usage of all sites. It takes into account the cooling and other overhead that supports the equipment.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by (site) (hw_host_power_watts) * avg by (site) (hw_site_pue_ratio))",
     "legendFormat": "Total Power * PUE"
    }
   ]
  },
  {
   "title": "Total Power * PUE",
   "type": "timeseries",
   "description": "Total current power usage across all sites, multiplied by the site's PUE, displayed as a graph.\n\nThis number represents the actual power usage of all sites. It takes into account the cooling and other overhead that supports the equipment.",
   "gridPos": { "h": 11, "w": 8, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(sum by (site) (hw_host_power_watts) * avg by (site) (avg_over_time(hw_site_pue_ratio{site=~\"$site\"}[2h])))",
     "legendFormat": "Total Power * PUE"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 10 },
   "options": {
    "content": "<h3 style=\"background-color:DimGray\"><center>Live Data</center></h3>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 9, "x": 15, "y": 10 },
   "options": {
    "content": "<h3 style=\"background-color:DimGray\"><center>Cumulative Data</center></h3>"
   }
  },
  {
   "title": "Today's Live Consumption ",
   "type": "stat",
   "description": "Today's total power consumption for all sites.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by (site) (increase(hw_host_energy_joules_total{site !=\"\"}[$__range])) * avg_over_time(avg by (site) (hw_site_pue_ratio)[$__range:5m])) / 3600",
     "legendFormat": "Today's Live Consumption "
    }
   ]
  },
  {
   "title": "Daily Consumption",
   "type": "stat",
   "description": "The overall power consumption reported for all sites in the last 24 hours.\n\nIf less than 24 hours of data is available, this value is estimated based on the past collected data.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(sum by (site) (hw_host_power_watts)[1d:5m]) * avg_over_time(avg by (site) (hw_site_pue_ratio)[1d:5m])) * 24",
     "legendFormat": "Daily Consumption"
    }
   ]
  },
  {
   "title": "Daily Cost",
   "type": "stat",
   "description": "The overall energy cost of all sites for the last 24 hours.\n\nIf less than 24 hours of data is available, this value is estimated based on past collected data.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(sum by (site) (hw_host_power_watts)[1d:5m]) * avg_over_time(avg by (site) (hw_site_pue_ratio)[1d:5m]) * avg_over_time(avg by (site) (hw_site_electricity_cost)[1d:5m])) * 24 / 1000",
     "legendFormat": "Daily Cost"
    }
   ]
  },
  {
   "title": "Daily CO₂ Emissions",
   "type": "stat",
   "description": "The overall volume of CO₂ emitted by all the sites for the last 24 hours.\n\nIf less than 24 hours of data is available, this value is estimated based on the past collected data.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(sum by (site) (hw_host_power_watts)[1d:5m]) * avg_over_time(avg by (site) (hw_site_pue_ratio)[1d:5m]) * avg_over_time(avg by (site) (hw_site_carbon_intensity_grams)[1d:5m])) * 24 / 1000 / 1000 / 1000",
     "legendFormat": "Daily CO₂ Emissions"
    }
   ]
  },
  {
   "title": "Total Power",
   "type": "stat",
   "description": "Total current power usage of all hosts across all sites.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(hw_host_power_watts) ", "legendFormat": "Total Power" }
   ]
  },
  {
   "title": "Today's Live Cost",
   "type": "stat",
   "description": "Today's total power cost for all sites.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by (site) (increase(hw_host_energy_joules_total[$__range])) * avg_over_time(avg by (site) (hw_site_pue_ratio)[$__range:5m]) * avg_over_time(avg by (site) (hw_site_electricity_cost)[$__range:5m])) / 3600 / 1000",
     "legendFormat": "Today's Live Cost"
    }
   ]
  },
  {
   "title": "Monthly Consumption",
   "type": "stat",
   "description": "The overall power consumption reported for all sites during the last 30 days.\n\nIf less than 30 days of data is available, this value is estimated based on past collected data.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(sum by (site) (hw_host_power_watts)[30d:1h]) * avg_over_time(avg by (site) (hw_site_pue_ratio)[30d:1h])) * 30.437 * 24",
     "legendFormat": "Monthly Consumption"
    }
   ]
  },
  {
   "title": "Monthly Cost",
   "type": "stat",
   "description": "The overall energy cost of all sites for the last 30 days.\n\nIf less than 30 days of data is available, this value is estimated based on past collected data.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(sum by (site) (hw_host_power_watts)[30d:1h]) * avg_over_time(avg by (site) (hw_site_pue_ratio)[30d:1h]) * avg_over_time(avg by (site) (hw_site_electricity_cost)[30d:1h])) * 30.437 * 24 / 1000",
     "legendFormat": "Monthly Cost"
    }
   ]
  },
  {
   "title": "Monthly CO₂ Emissions",
   "type": "stat",
   "description": "The overall volume of CO₂ emitted by all the sites for the last 30 days.\n\nIf less than 30 days of data is available, this value is estimated based on the past collected data.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(sum by (site) (hw_host_power_watts)[30d:1h]) * avg_over_time(avg by (site) (hw_site_pue_ratio)[30d:1h]) * avg_over_time(avg by (site) (hw_site_carbon_intensity_grams)[30d:1h])) * 30.467 * 24 / 1000 / 1000 / 1000",
     "legendFormat": "Monthly CO₂ Emissions"
    }
   ]
  },
  {
   "title": "Margin of Error",
   "type": "stat",
   "description": "The power consumption's margin of error.\n\nThis value is based on the number of hosts that report measured power consumptions and the number of hosts whose power consumption is estimated.\n\nWhen the power consumed by a host cannot be read, Hardware Sentry estimates this value based on the host's components (CPUs, disks, network interfaces, etc.) and their usage.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(hw_host_power_watts{quality=\"estimated\"} * 15) + sum(hw_host_power_watts{quality=\"measured\"} * 5) + 10000 * (sum(present_over_time(hardware_sentry_host_configured[1h])) - (count(max by (host_id) (hardware_sentry_connector_status{state=\"ok\"} == 1))))) / (sum(hw_host_power_watts) + 100 * (sum(present_over_time(hardware_sentry_host_configured[1h])) - (count(max by (host_id) (hardware_sentry_connector_status{state=\"ok\"} == 1)))))",
     "legendFormat": "Margin of Error"
    }
   ]
  },
  {
   "title": "Today's Live CO₂ Emissions",
   "type": "stat",
   "description": "Today's volume of CO₂ emissions for all sites.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by (site) (increase(hw_host_energy_joules_total[$__range])) * avg_over_time(avg by (site) (hw_site_pue_ratio)[$__range:5m]) * avg_over_time(avg by (site) (hw_site_carbon_intensity_grams)[$__range:5m])) / 3600 / 1000 / 1000 / 1000",
     "legendFormat": "Today's Live CO₂ Emissions"
    }
   ]
  },
  {
   "title": "Yearly Consumption",
   "type": "stat",
   "description": "The overall power consumption reported for all sites during the last year.\n\nIf less than 365 days of data is available, this value is estimated based on past collected data.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(sum by (site) (hw_host_power_watts)[1y:1d]) * avg_over_time(avg by (site) (hw_site_pue_ratio)[1y:1d])) * 365 * 24",
     "legendFormat": "Yearly Consumption"
    }
   ]
  },
  {
   "title": "Yearly Cost",
   "type": "stat",
   "description": "The overall energy cost of all sites for the past year.\n\nIf less than 365 days of data is available, this value is estimated based on past collected data.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(sum by (site) (hw_host_power_watts)[1y:1d]) * avg_over_time(avg by (site) (hw_site_pue_ratio)[1y:1d]) * avg_over_time(avg by (site) (hw_site_electricity_cost)[1y:1d])) * 365 * 24 / 1000",
     "legendFormat": "Yearly Cost"
    }
   ]
  },
  {
   "title": "Yearly CO₂ Emissions",
   "type": "stat",
   "description": "The overall volume of CO₂ emitted by all the sites for the past year.\n\nIf less than 365 days of data is available, this value is estimated based on the past collected data.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(sum by (site) (hw_host_power_watts)[1y:1d]) * avg_over_time(avg by (site) (hw_site_pue_ratio)[1y:1d]) * avg_over_time(avg by (site) (hw_site_carbon_intensity_grams)[1y:1d])) * 365 * 24 / 1000 / 1000 / 1000",
     "legendFormat": "Yearly CO₂ Emissions"
    }
   ]
  },
  { "title": "Sites", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "avg by (site) (avg_over_time(hw_site_electricity_cost{site != \"\"}[1d]))"
    },
    {
     "expr": "avg by (site) (avg_over_time(hw_site_carbon_intensity_grams{site != \"\"}[1d]))"
    },
    {
     "expr": "avg by (site) (avg_over_time(hw_site_pue_ratio{site != \"\"}[1d]))"
    },
    {
     "expr": "sum by (site) (avg_over_time(hw_host_power_watts{site != \"\"}[1d]))"
    },
    {
     "expr": "sum by (site) (avg_over_time(hardware_sentry_host_up[1d]))"
    },
    {
     "expr": "(sum by (site) (avg_over_time(hardware_sentry_host_up[1d]))) / scalar(sum(avg_over_time(hardware_sentry_host_up[1d])))"
    },
    {
     "expr": "avg by (site) (avg_over_time(hw_host_ambient_temperature_celsius{site != \"\"}[1d]))"
    },
    {
     "expr": "min by (site) (min_over_time(hw_host_heating_margin_celsius{site != \"\"}[1d]))"
    }
   ]
  },
  {
   "title": "Yearly Consumption",
   "type": "barchart",
   "description": "The sites' yearly power consumption.\n\nThese values are estimated according to the past data if less than a year of data has been collected.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "avg_over_time(sum by (site) (hw_host_power_watts)[1y:1d]) * avg_over_time(avg by (site) (hw_site_pue_ratio)[1y:1d]) * 365 * 24",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "Yearly Cost",
   "type": "barchart",
   "description": "The sites' yearly cost.\n\nThese values are estimated according to the past data if less than a year of data has been collected.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "avg_over_time(sum by (site) (hw_host_power_watts)[1y:1d]) * avg_over_time(avg by (site) (hw_site_pue_ratio)[1y:1d]) * avg_over_time(avg by (site) (hw_site_electricity_cost)[1y:1d]) * 365 * 24 / 1000",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "Yearly CO₂",
   "type": "barchart",
   "description": "The sites' yearly CO₂ emissions. \n\nThese values are estimated according to the past data if less than a year of data has been collected.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "targets": [
    {
     "expr": "avg_over_time(sum by (site) (hw_host_power_watts)[1y:1d]) * avg_over_time(avg by (site) (hw_site_pue_ratio)[1y:1d]) * avg_over_time(avg by (site) (hw_site_carbon_intensity_grams)[1y:1d]) * 365 * 24 / 1000 / 1000 / 1000",
     "legendFormat": "{{site}}"
    }
   ]
  },
  { "title": "Power and Host Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Top Consumers",
   "type": "bargauge",
   "description": "The 10 hosts that currently consume the most energy across all sites.",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "topk(10, hw_host_power_watts)", "legendFormat": "{{site}}: {{host_name}} " }
   ]
  },
  {
   "title": "Power per Host Type",
   "type": "piechart",
   "description": "The power consumption distribution by host types: compute (server), storage and network.",
   "gridPos": { "h": 9, "w": 4, "x": 5, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (host_type) (hw_host_power_watts)",
     "legendFormat": "{{host_type}}"
    }
   ]
  },
  {
   "title": "Power per Platform Type",
   "type": "piechart",
   "description": "The power consumption distribution across platform types: \nHP-UX, IBM AIX, Management (i.e management card), Microsoft Windows, Linux, \nOracle Solaris and Storage.",
   "gridPos": { "h": 9, "w": 5, "x": 9, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (os_type) (hw_host_power_watts)",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "Hosts Type",
   "type": "piechart",
   "description": "The total number of hosts per type: compute (server), storage and network.",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (host_type) (hw_host_configured)",
     "legendFormat": "{{host_type}}"
    }
   ]
  },
  {
   "title": "Hosts Vendor",
   "type": "piechart",
   "description": "The hosts distribution per manufacturer.",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (vendor) (label_replace(hw_status{hw_type=\"enclosure\", state=\"present\"}, \"vendor\", \"Unknown\", \"vendor\", \"^$\"))",
     "legendFormat": "{{vendor}}"
    }
   ]
  },
  { "title": "Hosts Temperatures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Hosts Ambient Temperature",
   "type": "stat",
   "description": "The 25 hosts reporting the hottest ambient temperature.\n\nClick on a host for details.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "topk(25, hw_host_ambient_temperature_celsius)"
    }
   ]
  },
  {
   "title": "Hosts Highest Temperature Sensor ",
   "type": "stat",
   "description": "The temperature sensors reporting the highest temperatures at the moment.\n\nClick on a temperature for details.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "topk(25, max by (site, host_name) (hw_temperature_celsius))"
    }
   ]
  },
  { "title": "History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Daily Energy Consumption (last 30 days)",
   "type": "barchart",
   "description": "The overall daily energy consumption for the past 30 days, as reported.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(sum by (site) (hw_host_power_watts)[1d:5m]) * avg_over_time(avg by (site) (hw_site_pue_ratio)[1d:5m])) * 24 + ignoring(year, month, day) group_right\r\n  count_values without() (\"year\", year(timestamp(\r\n    count_values without() (\"month\", month(timestamp(\r\n\t\t\tcount_values without() (\"day\", day_of_month(timestamp(\r\n        sum((sum by (site) (increase(hw_host_energy_joules_total{site != \"\"} [1d]))) / avg by (site) (increase(timestamp(hw_host_energy_joules_total{site != \"\"})[1d:1d])) * 24 * avg by (site) (hw_site_pue_ratio{site != \"\"}))\r\n\t\t\t\t)))\r\n    )))\r\n  ))) * 0",
     "legendFormat": "{{unit}}"
    }
   ]
  },
  { "title": "Hardware Sentry Agents Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Collect Started",
   "type": "stat",
   "description": "Time since the collect of data by Hardware Sentry was first started.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min_over_time(timestamp(hw_host_configured)[1y:1w])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 18, "x": 3, "y": 71 },
   "targets": [
    {
     "expr": "last_over_time(timestamp(hardware_sentry_agent_info)[6h:])"
    }
   ]
  },
  { "title": "Dashboard Version", "type": "stat", "gridPos": { "h": 5, "w": 3, "x": 21, "y": 71 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } }
 ]
}