{
 "title": "Hardware Sentry - Site",
 "tags": [ "hw_site" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "site",
    "label": "Site",
    "query": {
     "query": "label_values(hw_host_configured, site)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overall Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "<h1 style=\"\">\r\n  <center>$site</center>\r\n</h1>"
   }
  },
  {
   "title": "Hosts",
   "type": "stat",
   "description": "The number of hosts currently configured to be monitored.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(present_over_time(hardware_sentry_host_configured{site=~\"$site\"}[1h]))",
     "legendFormat": "Hosts"
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "stat",
   "description": "The percentage of monitored hosts.\n\nA monitored host is a host with at least one responding connector.",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max by (host_id, site) (hardware_sentry_connector_status{state=\"ok\", site=~\"$site\"} == 1)) / sum(present_over_time(hardware_sentry_host_configured{site=~\"$site\"}[1h]))",
     "legendFormat": "Coverage"
    }
   ]
  },
  {
   "title": "Critical Alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS_FOR_STATE{severity=\"critical\", site=~\"$site\"})",
     "legendFormat": "Critical Alerts"
    }
   ]
  },
  {
   "title": "Warning Alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS_FOR_STATE{severity=\"warn\", site=~\"$site\"})",
     "legendFormat": "Warning Alerts"
    }
   ]
  },
  {
   "title": "Host Types",
   "type": "piechart",
   "description": "The total number of hosts per type: compute (server), storage and network.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (host_type) (hardware_sentry_host_up{site=~\"$site\"})",
     "legendFormat": "{{host_type}}"
    }
   ]
  },
  {
   "title": "Hosts Vendors",
   "type": "piechart",
   "description": "The hosts distribution per manufacturer.",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (vendor) (label_replace(hw_status{hw_type=\"enclosure\", site=~\"$site\", state=\"present\"}, \"vendor\", \"Unknown\", \"vendor\", \"^$\"))",
     "legendFormat": "{{vendor}}"
    }
   ]
  },
  {
   "title": "PUE",
   "type": "timeseries",
   "description": "The average of the Power Usage Effectiveness over 2 hours.",
   "gridPos": { "h": 4, "w": 5, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(hw_site_pue_ratio{site=~\"$site\"}[2h]))",
     "legendFormat": "PUE"
    }
   ]
  },
  {
   "title": "PUE (24 hrs)",
   "type": "stat",
   "description": "The average of the Power Usage Effectiveness over 24 hours.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(hw_site_pue_ratio{site=~\"$site\"}[1d]))",
     "legendFormat": "PUE (24 hrs)"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "stat",
   "description": "The total number of CPUs currently monitored.",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hw_status{site=~\"$site\", hw_type=\"cpu\", state=\"present\"})",
     "legendFormat": "CPUs"
    }
   ]
  },
  {
   "title": "Connected NICs",
   "type": "stat",
   "description": "The total number of connected network cards.",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hw_network_up{site=~\"$site\"})",
     "legendFormat": "Connected NICs"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "stat",
   "description": "The total disk space in the site.",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hw_physical_disk_size_bytes{site=~\"$site\"})",
     "legendFormat": "Disk Space"
    }
   ]
  },
  {
   "title": "Network Tx",
   "type": "stat",
   "description": "The total volume of network transfers in the site.",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hw_network_io_bytes_total{site=~\"$site\", direction=\"transmit\"})",
     "legendFormat": "Network Transfers"
    }
   ]
  },
  {
   "title": "CO₂ Intensity",
   "type": "stat",
   "description": "The CO₂ electricity emissions, as provided in the configuration file.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hw_site_carbon_intensity_grams{site=~\"$site\"})",
     "legendFormat": "CO₂ Intensity"
    }
   ]
  },
  {
   "title": "Electricity Cost",
   "type": "stat",
   "description": "Electricity cost, as provided in the configuration file.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hw_site_electricity_cost{site=~\"$site\"})",
     "legendFormat": "Electricity Cost"
    }
   ]
  },
  { "title": "Power, Costs and CO₂ Emissions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Total Power * PUE",
   "type": "stat",
   "description": "The site's current power usage multiplied by the site's PUE.\n\nThis number represents the site's actual power usage. It takes into account the cooling and other overhead that supports the equipment.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hw_host_power_watts{site=~\"$site\"}) * scalar(avg(hw_site_pue_ratio{site=~\"$site\"}))",
     "legendFormat": "Total Power * PUE"
    }
   ]
  },
  {
   "title": "Total Power * PUE",
   "type": "timeseries",
   "description": "The site's current power usage multiplied by the site's PUE, displayed as a graph.\n\nThis number represents the actual power usage of a data center. It takes into account the cooling and other overhead that supports the equipment.",
   "gridPos": { "h": 11, "w": 8, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(hw_host_power_watts{site=~\"$site\"}) * scalar(avg(avg_over_time(hw_site_pue_ratio{site=~\"$site\"}[2h])))",
     "legendFormat": "Total Power * PUE"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 11 },
   "options": {
    "content": "<h3 style=\"background-color:Grey\"><center>Live Data</center></h3>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 9, "x": 15, "y": 11 },
   "options": {
    "content": "<h3 style=\"background-color:Grey\"><center>Cumulative Data</center></h3>"
   }
  },
  {
   "title": "Today's Live Consumption",
   "type": "stat",
   "description": "Today's power consumption for the site.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(hw_host_energy_joules_total{site=~\"$site\"}[$__range])) * avg_over_time(avg(hw_site_pue_ratio{site=~\"$site\"})[$__range:5m]) / 3600 ",
     "legendFormat": "Today's Live Consumption"
    }
   ]
  },
  {
   "title": "Daily Consumption",
   "type": "stat",
   "description": "The overall power consumption reported for the site in the last 24 hours.\n\nIf less than 24 hours of data is available, this value is estimated based on the past collected data.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(sum(hw_host_power_watts{site=~\"$site\"})[1d:5m]) * avg_over_time(avg(hw_site_pue_ratio{site=~\"$site\"})[1d:5m])) * 24",
     "legendFormat": "Daily Consumption"
    }
   ]
  },
  {
   "title": "Daily Cost",
   "type": "stat",
   "description": "The overall energy cost reported for the site during the last 24 hours.\n\nIf less than 24 hours of data is available, this value is estimated based on the past collected data.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(sum(hw_host_power_watts{site=~\"$site\"})[1d:5m]) * avg_over_time(avg(hw_site_pue_ratio{site=~\"$site\"})[1d:5m]) * avg_over_time(avg(hw_site_electricity_cost{site=~\"$site\"})[1d:5m])) * 24 / 1000",
     "legendFormat": "Daily Cost"
    }
   ]
  },
  {
   "title": "Daily CO₂ Emissions",
   "type": "stat",
   "description": "The overall volume of CO₂ emitted by the site during the last 24 hours.\n\nIf less than 24 hours of data is available, this value is estimated based on the past collected data.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(sum(hw_host_power_watts{site=~\"$site\"})[1d:5m]) * avg_over_time(avg(hw_site_pue_ratio{site=~\"$site\"})[1d:5m]) * avg_over_time(avg(hw_site_carbon_intensity_grams{site=~\"$site\"})[1d:5m])) * 24 / 1000 / 1000",
     "legendFormat": "Daily CO₂ Emissions"
    }
   ]
  },
  {
   "title": "Total Power",
   "type": "stat",
   "description": "The total current power consumption of all the hosts in the site.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hw_host_power_watts{site=~\"$site\"})",
     "legendFormat": "Total Power"
    }
   ]
  },
  {
   "title": "Today's Live Cost",
   "type": "stat",
   "description": "Today's power cost for the site.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(hw_host_energy_joules_total{site=~\"$site\"}[$__range])) * avg_over_time(avg(hw_site_pue_ratio{site=~\"$site\"})[$__range:5m]) * avg_over_time(avg(hw_site_electricity_cost{site=~\"$site\"})[$__range:5m]) / 3600 / 1000",
     "legendFormat": "Today's Live Cost"
    }
   ]
  },
  {
   "title": "Monthly Consumption",
   "type": "stat",
   "description": "The overall power consumption reported for the site during the last 30 days.\n\nIf less than 30 days of data is available, this value is estimated based on past collected data.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(sum(hw_host_power_watts{site=~\"$site\"})[30d:1h]) * avg_over_time(avg(hw_site_pue_ratio{site=~\"$site\"})[30d:1h])) * 30.437 * 24",
     "legendFormat": "Monthly Consumption"
    }
   ]
  },
  {
   "title": "Monthly Cost",
   "type": "stat",
   "description": "The overall energy cost reported for the site during the last 30 days.\n\nIf less than 30 days of data is available, this value is estimated based on past collected data.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(sum(hw_host_power_watts{site=~\"$site\"})[30d:1h]) * avg_over_time(avg(hw_site_pue_ratio{site=~\"$site\"})[30d:1h]) * avg_over_time(avg(hw_site_electricity_cost{site=~\"$site\"})[30d:1h])) * 30.437 * 24 /1000",
     "legendFormat": "Monthly Cost"
    }
   ]
  },
  {
   "title": "Monthly CO₂ Emissions",
   "type": "stat",
   "description": "The overall volume of CO₂ emitted by the site during the last 30 days.\n\nIf less than 30 days of data is available, this value is estimated based on the past collected data.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(sum(hw_host_power_watts{site=~\"$site\"})[30d:1h]) * avg_over_time(avg(hw_site_pue_ratio{site=~\"$site\"})[30d:1h]) * avg_over_time(avg(hw_site_carbon_intensity_grams{site=~\"$site\"})[30d:1h])) * 30.437 * 24 / 1000 / 1000 / 1000",
     "legendFormat": "Monthly CO₂ Emissions"
    }
   ]
  },
  {
   "title": "Margin of Error",
   "type": "stat",
   "description": "The percentage of possible deviation from an exact power consumption value.\n\nThis value is based on the collected data of monitored hosts reporting power consumption and estimated values for hosts not reporting their power consumption.\n\nWhen the power consumed by a host cannot be read, Hardware Sentry estimates this value based on the typical consumption of a host's components (CPUs, disks, network interfaces, etc.).",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(hw_host_power_watts{quality=\"estimated\", site=\"$site\"} * 15) + sum(hw_host_power_watts{quality=\"measured\", site=\"$site\"} * 5) + 10000 * (sum(present_over_time(hardware_sentry_host_configured{site=\"$site\"}[1h])) - (count(max by (host_id) (hardware_sentry_connector_status{state=\"ok\", site=\"$site\"} == 1))))) / (sum(hw_host_power_watts{site=\"$site\"}) + 100 * (sum(present_over_time(hardware_sentry_host_configured{site=\"$site\"}[1h])) - (count(max by (host_id) (hardware_sentry_connector_status{state=\"ok\", site=\"$site\"} == 1)))))",
     "legendFormat": "Margin of Error"
    }
   ]
  },
  {
   "title": "Today's Live CO₂ Emissions",
   "type": "stat",
   "description": "Today's volume of CO₂ emissions for the site.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(hw_host_energy_joules_total{site=~\"$site\"}[$__range])) * avg_over_time(avg(hw_site_pue_ratio{site=~\"$site\"})[$__range:5m]) * avg_over_time(avg(hw_site_carbon_intensity_grams{site=~\"$site\"})[$__range:5m]) / 3600 / 1000 / 1000",
     "legendFormat": "Today's Live CO₂ Emissions"
    }
   ]
  },
  {
   "title": "Yearly Consumption",
   "type": "stat",
   "description": "The overall power consumption reported for the site during the last year.\n\nIf less than 365 days of data is available, this value is estimated based on past collected data.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(sum(hw_host_power_watts{site=~\"$site\"})[1y:1d]) * avg_over_time(avg(hw_site_pue_ratio{site=~\"$site\"})[1y:1d])) * 365 * 24",
     "legendFormat": "Yearly Consumption"
    }
   ]
  },
  {
   "title": "Yearly Cost",
   "type": "stat",
   "description": "The overall energy cost reported for the site in the past year.\n\nIf less than 365 days of data is available, this value is estimated based on past collected data.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(sum(hw_host_power_watts{site=~\"$site\"})[1y:1d]) * avg_over_time(avg(hw_site_pue_ratio{site=~\"$site\"})[1y:1d]) * avg_over_time(avg(hw_site_electricity_cost{site=~\"$site\"})[1y:1d])) * 365 * 24 / 1000",
     "legendFormat": "Yearly Cost"
    }
   ]
  },
  {
   "title": "Yearly CO₂ Emissions",
   "type": "stat",
   "description": "The overall volume of CO₂ emitted by the site during the past year.\n\nIf less than 365 days of data is available, this value is estimated based on past collected data.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(sum(hw_host_power_watts{site=~\"$site\"})[1y:1d]) * avg_over_time(avg(hw_site_pue_ratio{site=~\"$site\"})[1y:1d]) * avg_over_time(avg(hw_site_carbon_intensity_grams{site=~\"$site\"})[1y:1d])) * 365 * 24 / 1000 / 1000 / 1000",
     "legendFormat": "Yearly CO₂ Emissions"
    }
   ]
  },
  { "title": "Site Temperature Optimization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Heating Margin",
   "type": "stat",
   "description": "The number of degrees Celsius (°C) remaining before the temperature of a host in the site reaches its closest warning temperature threshold.\n\nIt is advised to keep the heating margin above 5°C.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(hw_host_heating_margin_celsius{site=~\"$site\"}[1d]))",
     "legendFormat": "Heating Margin"
    }
   ]
  },
  {
   "title": "Monitoring Confidence",
   "type": "stat",
   "description": "The percentage of hosts for which temperature readings are reported.",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(hw_host_ambient_temperature_celsius{site=~\"$site\"}) / sum(present_over_time(hw_host_configured{site=~\"$site\"}[1h])) * 100",
     "legendFormat": "Monitoring Confidence"
    }
   ]
  },
  {
   "title": "Site Heating Margin",
   "type": "timeseries",
   "description": "The lowest host's heating margin of all hosts in the site.",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "min(hw_host_heating_margin_celsius{site=\"$site\"})",
     "legendFormat": "Heating Margin"
    }
   ]
  },
  {
   "title": "Current Site Temperature",
   "type": "stat",
   "description": "The estimation of the site's temperature based on the ambient temperature of all hosts in the site.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hw_host_ambient_temperature_celsius{site=~\"$site\"})",
     "legendFormat": "Site Temperature"
    }
   ]
  },
  {
   "title": "Potential Yearly Energy Savings",
   "type": "stat",
   "description": "The estimated energy consumption cuts based on the current power consumption, heating margin, site temperature and recommended site temperature.\n\nIf the recommended site temperature is lower than the current site temperature, this number may be negative.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(hw_host_power_watts{site=~\"$site\"}[1d])) * (avg(avg_over_time(hw_site_pue_ratio{site=~\"$site\"}[1d])) - 1.15) * 24 * 365 * (clamp_max(avg(avg_over_time(hw_host_ambient_temperature_celsius{site=~\"$site\"}[1d])) + min(min_over_time(hw_host_heating_margin_celsius{site=~\"$site\"}[1d])) - 5 - ((avg(max_over_time(avg(hw_host_ambient_temperature_celsius{site=~\"$site\"})[1d:])) - avg(avg_over_time(hw_host_ambient_temperature_celsius{site=~\"$site\"}[1d])))), 29) - avg(avg_over_time(hw_host_ambient_temperature_celsius{site=~\"$site\"}[1d]))) * 0.05",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heating Margin Host Distribution",
   "type": "histogram",
   "description": "The number of hosts according to their heating margin.\n\nThe abscissa shows the heating margin.\nThe ordinate represents the number of hosts  for a given heating margin.",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "min by (host_name) (min_over_time(hw_host_heating_margin_celsius{site=~\"$site\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Potential Yearly Savings",
   "type": "stat",
   "description": "The estimated yearly savings based on the current power consumption, heating margin, site temperature and recommended site temperature.\n\nIf the recommended site temperature is lower than the current site temperature, this number may be negative.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(hw_host_power_watts{site=~\"$site\"}[1d])) * (avg(avg_over_time(hw_site_pue_ratio{site=~\"$site\"}[1d])) - 1.15) * 24 * 365 * (clamp_max(avg(avg_over_time(hw_host_ambient_temperature_celsius{site=~\"$site\"}[1d])) + min(min_over_time(hw_host_heating_margin_celsius{site=~\"$site\"}[1d])) - 5 - ((max_over_time(avg(hw_host_ambient_temperature_celsius{site=~\"$site\"})[1d:]) - avg(avg_over_time(hw_host_ambient_temperature_celsius{site=~\"$site\"}[1d])))), 29) - avg(avg_over_time(hw_host_ambient_temperature_celsius{site=~\"$site\"}[1d]))) * 0.05 * avg(avg_over_time(hw_site_electricity_cost{site=~\"$site\"}[1d])) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recommended Max Site Temperature",
   "type": "stat",
   "description": "The recommended site temperature based on the site's current heating margin, as well as the current and past site temperatures.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(clamp_max(avg(avg_over_time(hw_host_ambient_temperature_celsius{site=~\"$site\"}[1d])) * 2 + min(min_over_time(hw_host_heating_margin_celsius{site=~\"$site\"}[1d])) - max_over_time(avg(hw_host_ambient_temperature_celsius{site=~\"$site\"})[1d:]) - 5, 29), 15)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Potential Yearly CO₂ Reduction",
   "type": "stat",
   "description": "The estimated CO₂ emissions reduction based on the current power consumption, heating margin, site temperature and recommended site temperature.\n\nIf the recommended site temperature is lower than the current site temperature, this number may be negative.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(hw_host_power_watts{site=~\"$site\"}[1d])) * (avg(avg_over_time(hw_site_pue_ratio{site=~\"$site\"}[1d])) - 1.15) * 24 * 365 * (clamp_max(avg(avg_over_time(hw_host_ambient_temperature_celsius{site=~\"$site\"}[1d])) + min(min_over_time(hw_host_heating_margin_celsius{site=~\"$site\"}[1d])) - 5 - ((max_over_time(avg(hw_host_ambient_temperature_celsius{site=~\"$site\"})[1d:]) - avg(avg_over_time(hw_host_ambient_temperature_celsius{site=~\"$site\"}[1d])))), 29) - avg(avg_over_time(hw_host_ambient_temperature_celsius{site=~\"$site\"}[1d]))) * 0.05 * avg(avg_over_time(hw_site_carbon_intensity_grams{site=~\"$site\"}[1d])) / 1000 / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Hosts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(hw_host_energy_joules_total{site=~\"$site\"}[1d])"
    },
    {
     "expr": "min_over_time(hw_host_heating_margin_celsius{site=~\"$site\"}[1d])"
    },
    {
     "expr": "last_over_time(timestamp(hardware_sentry_host_up{site=~\"$site\"})[6h:])"
    },
    {
     "expr": "avg_over_time(hw_host_ambient_temperature_celsius{site=~\"$site\"}[1d])"
    }
   ]
  },
  { "title": "History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Daily Energy Consumption (last 30 days)",
   "type": "barchart",
   "description": "The site's daily energy consumption for the past 30 days, as reported.",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(sum(hw_host_power_watts{site=~\"$site\"})[1d:5m]) * avg_over_time(avg(hw_site_pue_ratio{site=~\"$site\"})[1d:5m])) * 24 + ignoring(year, month, day) group_right\r\n  count_values without() (\"year\", year(timestamp(\r\n    count_values without() (\"month\", month(timestamp(\r\n\t\t\tcount_values without() (\"day\", day_of_month(timestamp(\r\n        sum(increase(hw_host_energy_joules_total{site=~\"$site\"} [1d])) / avg(increase(timestamp(hw_host_energy_joules_total{site=~\"$site\"})[1d:1d])) * 24 * avg(hw_site_pue_ratio{site=~\"$site\"})\r\n\t\t\t\t)))\r\n    )))\r\n  ))) * 0",
     "legendFormat": "{{unit}}"
    }
   ]
  },
  { "title": "Hardware Sentry Agent Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Collect Started",
   "type": "stat",
   "description": "Time since the collect of data by Hardware Sentry was first started for the site.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min_over_time(timestamp(hw_host_configured{site=~\"$site\"})[1y:1d])"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 21, "x": 3, "y": 61 },
   "targets": [
    {
     "expr": "last_over_time(timestamp(hardware_sentry_agent_info{site=~\"$site\"})[6h:])"
    }
   ]
  }
 ]
}